## RG Bicep

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: PublishBuildArtifacts@1
  inputs:
    # PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    PathtoPublish: './'
    ArtifactName: 'drop'
    publishLocation: 'Container'